# Ascii document generator jazzy settings

copyright: Copyright 2017 Rien van der Lugt
author: Rien van der Lugt
module: Ascii
hide_documentation_coverage: true
xcodebuild_arguments: [-target, Ascii]
github_url: https://github.com/Balancingrock/Ascii
output: ~/Documents/Websites/sf/projects/ascii/reference
clean: true
theme: fullwidth
